version: '3.4'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "app"
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=production
    environment:
      NODE_ENV: production
    env_file:
      - ./.env
